version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis_feedback
    env_file:
      - .env
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  db:
    image: postgres:14
    container_name: db_feedback
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_hash:/var/lib/postgresql/data
volumes:
  redis-data:
  postgres_data_hash:
